/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package VentanaGrafica;

import javax.swing.JOptionPane;

import Control.ControladorAlquilerCompra;

/**
 *
 * @author juanjose
 */
public class AlquilerInstalacion extends javax.swing.JPanel {
	ControladorAlquilerCompra control;
    /**
     * Creates new form AlquilerMaterial
     */
    public AlquilerInstalacion(ControladorAlquilerCompra controlador) {
    	control = controlador;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bAlquilar = new javax.swing.JButton();
        jlTipo = new javax.swing.JLabel();
        jcbTipo = new javax.swing.JComboBox();
        jlHoras = new javax.swing.JLabel();
        jtxHoras = new javax.swing.JTextField();
        jlTitulo = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 204, 255));

        bAlquilar.setText("Alquilar");
        bAlquilar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAlquilarActionPerformed(evt);
            }
        });

        jlTipo.setText("Tipo");

        jcbTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Futbol7", "Futbol11", "Baloncesto", "Tenis", "Padel" }));

        jlHoras.setText("Horas");

        jlTitulo.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jlTitulo.setForeground(new java.awt.Color(102, 102, 102));
        jlTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlTitulo.setText("ALQUILER INSTALACION");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlHoras))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jcbTipo, javax.swing.GroupLayout.Alignment.TRAILING, 0, 94, Short.MAX_VALUE)
                            .addComponent(jtxHoras))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bAlquilar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(12, 12, 12)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jlTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bAlquilar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlHoras)
                    .addComponent(jtxHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bAlquilarActionPerformed(java.awt.event.ActionEvent evt) {
       if(control.alquilarInstalacion(jcbTipo.getSelectedItem().toString(), jtxHoras.getText()))
    	   JOptionPane.showConfirmDialog(bAlquilar, "Alquilado correctamente", "OK", JOptionPane.INFORMATION_MESSAGE);
       else
    	   JOptionPane.showConfirmDialog(bAlquilar, "Error al alquilar la instalacion", "ERROR", JOptionPane.ERROR_MESSAGE);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAlquilar;
    private javax.swing.JComboBox jcbTipo;
    private javax.swing.JLabel jlHoras;
    private javax.swing.JLabel jlTipo;
    private javax.swing.JLabel jlTitulo;
    private javax.swing.JTextField jtxHoras;
    // End of variables declaration//GEN-END:variables
}
