/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package VentanaGrafica;

import java.sql.Date;
import java.util.ArrayList;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

import enums.UsuarioEnum;
import transfers.Material;
import transfers.Socio;
import transfers.Usuario;
import Control.ControladorAlquilerCompra;
import Control.ControladorMateriales;
import Control.ControladorUsuarios;

/**
 *
 * @author juanjose
 */
public class AlquilerMaterial extends javax.swing.JPanel implements ListSelectionListener {

	private ControladorAlquilerCompra control;
	private ControladorUsuarios controlUsuarios;
	private ControladorMateriales controlMaterial;
	private ArrayList<Material> lista;
	private ArrayList<Socio> listaSocios;
	boolean[] horas;
    /**
     * Creates new form AlquilerMaterial
     * @param controlAlquilerCompra 
     */
    public AlquilerMaterial(ControladorMateriales controlMaterial, ControladorAlquilerCompra controlador, ControladorUsuarios controlUSuario, boolean muestraLista) {
    	this.controlMaterial = controlMaterial;
    	this.control = controlador;
    	this.controlUsuarios = controlUSuario;
        initComponents(muestraLista);
        jScrollPane3.setVisible(muestraLista);
        listaUsuarios.setVisible(muestraLista);
        etiquetaUsuarios.setVisible(muestraLista);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents(boolean muestraLista) {

        tituloAlqMaterial = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaMaterial = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaHoras = new javax.swing.JList();
        etiquetaMaterial = new javax.swing.JLabel();
        etiquetaHoras = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listaUsuarios = new javax.swing.JList();
        etiquetaUsuarios = new javax.swing.JLabel();
        botonAlquilar = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 204, 255));

        tituloAlqMaterial.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        tituloAlqMaterial.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloAlqMaterial.setText("ALQUILER MATERIAL");

        jScrollPane1.setViewportView(listaMaterial);

        jScrollPane2.setViewportView(listaHoras);

        etiquetaMaterial.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        etiquetaMaterial.setText("Materiales");

        etiquetaHoras.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        etiquetaHoras.setText("Horas");

        jScrollPane3.setViewportView(listaUsuarios);

        etiquetaUsuarios.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        etiquetaUsuarios.setText("Usuarios");
        
        DefaultListModel<Material> modeloListaMaterial = new DefaultListModel<Material>();
    	lista = controlMaterial.listaMateriales();
    	if(!lista.isEmpty()){
    		for(int i = 0; i < lista.size(); i++){
    			modeloListaMaterial.add(i, lista.get(i));
    		}
    	}
    	listaMaterial.removeAll();
        listaMaterial.setModel(modeloListaMaterial);
        listaMaterial.addListSelectionListener(this);
        
       if(muestraLista){ 
        
        DefaultListModel<Socio> modeloLista = new DefaultListModel<Socio>();
    	listaSocios = controlUsuarios.listaSocios();
    	if(!listaSocios.isEmpty()){
    		for(int i = 0; i < listaSocios.size(); i++){
        		modeloLista.add(i, listaSocios.get(i));
        	}
    	}
       
    	listaUsuarios.removeAll();
        listaUsuarios.setModel(modeloLista);
        
       }
        botonAlquilar.setText("Alquilar Material");
        botonAlquilar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAlquilarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(etiquetaMaterial)
                                .addGap(51, 51, 51)
                                .addComponent(etiquetaHoras)
                                .addGap(57, 57, 57)
                                .addComponent(etiquetaUsuarios))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(botonAlquilar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(tituloAlqMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(tituloAlqMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaHoras)
                    .addComponent(etiquetaMaterial)
                    .addComponent(etiquetaUsuarios))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonAlquilar)
                .addContainerGap(44, Short.MAX_VALUE))
        );
    }                       

    private void botonAlquilarActionPerformed(java.awt.event.ActionEvent evt) {
    	if(!this.listaMaterial.isSelectionEmpty() && !this.listaHoras.isSelectionEmpty() && !this.listaUsuarios.isSelectionEmpty()){
	    	Material mat = this.lista.get(listaMaterial.getSelectedIndex());
	    	java.util.Date fecha1 = new java.util.Date();
	    	long date = fecha1.getTime();
	    	Date fecha = new Date(date);
	    	//Date fecha = new Date(fecha1.getYear(), fecha1.getMonth(), fecha1.getDate());
	    	int hora =  Integer.parseInt((String) listaHoras.getSelectedValue());
	    	String socio = listaSocios.get(listaUsuarios.getSelectedIndex()).getNick();
	    	if(control.alquilarMaterial(mat.getId(), socio, hora, fecha)){
	    		DefaultListModel<String> modeloListaHoras = new DefaultListModel<String>();
				horas = controlMaterial.VerHoras(mat.getId());
		    	if(horas.length != 0){
		    		int a = 0;
		    		for(int i = 0; i < horas.length; i++){
		    			if(horas[i]){
		    				modeloListaHoras.add(a, Integer.toString(i + 9));
		    				a++;
		    			}
		    		}
		    	}
		    	listaHoras.removeAll();
		    	listaHoras.setModel(modeloListaHoras);
		    	JOptionPane.showMessageDialog(null,  "Exito al alquilar el material","EXITO", JOptionPane.INFORMATION_MESSAGE);
	    	}
	    	else
	    		JOptionPane.showConfirmDialog(null, "Error al alquilar el material", "ERROR", JOptionPane.INFORMATION_MESSAGE);
    	}else{
    		JOptionPane.showConfirmDialog(null, "Debes seleccionar todos los componentes", "ERROR", JOptionPane.INFORMATION_MESSAGE);

    	}
    }                                             


    // Variables declaration - do not modify                     
    private javax.swing.JButton botonAlquilar;
    private javax.swing.JLabel etiquetaHoras;
    private javax.swing.JLabel etiquetaMaterial;
    private javax.swing.JLabel etiquetaUsuarios;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList listaHoras;
    private javax.swing.JList listaMaterial;
    private javax.swing.JList listaUsuarios;
    private javax.swing.JLabel tituloAlqMaterial;
    private VentanaUsuario ventUsuario;
    private Usuario socio;
    // End of variables declaration                   
	@Override
	
	public void valueChanged(ListSelectionEvent arg0) {
		// TODO Auto-generated method stub
		if(listaMaterial.getSelectedIndex() >= 0){
			Material mat = this.lista.get(listaMaterial.getSelectedIndex());
			DefaultListModel<String> modeloListaHoras = new DefaultListModel<String>();
			horas = controlMaterial.VerHoras(mat.getId());
	    	if(horas.length != 0){
	    		int a = 0;
	    		for(int i = 0; i < horas.length; i++){
	    			if(horas[i]){
	    				modeloListaHoras.add(a, Integer.toString(i + 9));
	    				a++;
	    			}
	    		}
	    	}
	    	listaHoras.removeAll();
	    	listaHoras.setModel(modeloListaHoras);
		}
	}
}
