package VentanaGrafica;

import java.util.ArrayList;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

import transfers.Clases;
import transfers.Entrenador;
import Control.ControladorClases;
import Control.ControladorInstalaciones;
import Control.ControladorUsuarios;

/**
 *
 * @author juanjose
 */
public class AltaClases extends javax.swing.JPanel {
	private ControladorUsuarios controlUsuarios;
	private ControladorClases controlClases;
	private boolean modificar;
	private Clases clase;
    /**
     * Creates new form PanelClases
     */
    public AltaClases(ControladorUsuarios controlUsu, ControladorClases controlCla) {
    	modificar = false;
    	controlClases = controlCla;
    	controlUsuarios = controlUsu;
        initComponents();
        cargaEntrenadores();
    }
    
    public AltaClases(Clases clase, ControladorUsuarios controlUsu, ControladorClases controlCla) {
    	this.clase = clase;
    	modificar = true;
    	controlClases = controlCla;
    	controlUsuarios = controlUsu;
        initComponents();
        rellenaDatos();
        cargaEntrenadores();
    }

    private void rellenaDatos() {
    	jcTipoClase.setSelectedItem(clase.getClase().toString());
    	jcTipoDeporte.setSelectedItem(clase.getTipo().toString());
	}

	private void cargaEntrenadores() {
    	DefaultListModel<Entrenador> modeloLista = new DefaultListModel<Entrenador>();
    	ArrayList<Entrenador> listaUsuarios = controlUsuarios.listaEntrenador();
    	if(!listaUsuarios.isEmpty()){
    	for(int i = 0; i < listaUsuarios.size(); i++){
    		modeloLista.addElement(listaUsuarios.get(i));
    	}
    	}
    	listaEntrenadores.removeAll();
    	listaEntrenadores.setModel(modeloLista);
		
	}

	/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listaEntrenadores = new javax.swing.JList();
        jcTipoClase = new javax.swing.JComboBox();
        jcTipoDeporte = new javax.swing.JComboBox();
        bGuardar = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 204, 255));

        jScrollPane1.setViewportView(listaEntrenadores);

        jcTipoClase.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "INDIVIDUAL", "GRUPO" }));

        jcTipoDeporte.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "FUTBOL7", "FUTBOL11", "BALONCESTO", "TENIS", "PADEL" }));

        bGuardar.setText("Guardar");
        bGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jcTipoClase, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jcTipoDeporte, 0, 164, Short.MAX_VALUE))
                    .addComponent(bGuardar))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(28, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jcTipoClase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jcTipoDeporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bGuardar)
                        .addGap(37, 37, 37))))
        );
    }// </editor-fold>                        

    private void bGuardarActionPerformed(java.awt.event.ActionEvent evt) {                                         
        if(!listaEntrenadores.isSelectionEmpty()){
        	if(controlClases.altaClase(((Entrenador)listaEntrenadores.getSelectedValue()), jcTipoClase.getSelectedItem().toString(), jcTipoDeporte.getSelectedItem().toString()))
        		JOptionPane.showConfirmDialog(bGuardar, "Guardado Correctamente", "OK", JOptionPane.OK_OPTION);
        	else
        		JOptionPane.showConfirmDialog(bGuardar, "Error al guardar la Clase", "ERROR", JOptionPane.ERROR_MESSAGE);
        } 		
        else
        	JOptionPane.showConfirmDialog(bGuardar, "Selecciona un entrenador", "ERROR", JOptionPane.ERROR_MESSAGE);
        	
    }                                        


    // Variables declaration - do not modify                     
    private javax.swing.JButton bGuardar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox jcTipoClase;
    private javax.swing.JComboBox jcTipoDeporte;
    private javax.swing.JList listaEntrenadores;     
}
