/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package VentanaGrafica;

import javax.sound.midi.MidiDevice.Info;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;

import transfers.Instalaciones;
import enums.PistaEnum;
import enums.TipoEnum;
import Control.ControladorInstalaciones;

/**
 *
 * @author juanjose
 */
public class AltaInstalacion extends javax.swing.JPanel {
	private ControladorInstalaciones controlInstalaciones;
	private Instalaciones instalacion;
	
    /** 
     * Creates new form AltaPista
     */
    public AltaInstalacion(ControladorInstalaciones controladorInst) {
    	controlInstalaciones = controladorInst;
    	instalacion = new Instalaciones();
        initComponents();
        this.setVisible(true);
    }
    
    public AltaInstalacion(Instalaciones ins, ControladorInstalaciones controladorInst) {
    	controlInstalaciones = controladorInst;
    	instalacion = ins;
        initComponents();
        this.setVisible(true);
        jcDisponibilidad.setSelectedItem(ins.getDisponibilidad().toString());
        jcbTipo.setSelectedItem(ins.getTipo().toString());
        if(ins.getPista() == PistaEnum.CUBIERTA)
        	chkCubierta.setSelected(true);
        else if(ins.getPista() == PistaEnum.EXTERIOR)
        	chkExterior.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jlbPista = new javax.swing.JLabel();
        jlbTipo = new javax.swing.JLabel();
        jDisponibilidad = new javax.swing.JLabel();
        chkCubierta = new javax.swing.JRadioButton();
        chkExterior = new javax.swing.JRadioButton();
        jcbTipo = new javax.swing.JComboBox();
        btGuardar = new javax.swing.JButton();
        jcDisponibilidad = new javax.swing.JComboBox();

        jLabel5.setText("jLabel5");

        setBackground(new java.awt.Color(153, 204, 255));

        jlbPista.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jlbPista.setText("INSTALACION");

        jlbTipo.setText("Tipo");

        jDisponibilidad.setText("Disponibilidad");

        chkCubierta.setBackground(new java.awt.Color(153, 204, 255));
        chkCubierta.setText("Cubierta");

        chkExterior.setBackground(new java.awt.Color(153, 204, 255));
        chkExterior.setText("Exterior");

        jcbTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "FUTBOL7", "FUTBOL11", "BALONCESTO", "TENIS", "PADEL" }));

        btGuardar.setText("GUARDAR");
        btGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGuardarActionPerformed(evt);
            }
        });

        jcDisponibilidad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "LUNESAVIERNES", "FINESDESEMANA" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jlbTipo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jDisponibilidad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jcDisponibilidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btGuardar))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chkCubierta)
                        .addGap(63, 63, 63))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chkExterior)
                        .addGap(41, 41, 41))))
            .addGroup(layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(jlbPista)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jlbPista)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbTipo)
                    .addComponent(chkCubierta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jDisponibilidad)
                    .addComponent(jcDisponibilidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkExterior))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btGuardar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btGuardarActionPerformed(java.awt.event.ActionEvent evt) {
    	if(compruebaCampos()){
    		PistaEnum tipo = null;
    		if(chkCubierta.isSelected())
    			tipo = PistaEnum.CUBIERTA;
    		else 
    			tipo = PistaEnum.EXTERIOR;
    		if(controlInstalaciones.AltaInstalacion(jcDisponibilidad.getSelectedItem().toString(), jcbTipo.getSelectedItem().toString(), tipo)) {
    			JOptionPane.showConfirmDialog(btGuardar, "Guardado Correctamente", "OK", JOptionPane.OK_OPTION);
    		} else
    			JOptionPane.showConfirmDialog(btGuardar, "Error al guardar la instalacion", "ERROR", JOptionPane.ERROR_MESSAGE);		
    	}
    	else
    		JOptionPane.showConfirmDialog(btGuardar, "Introduce todos los campos", "ERROR", JOptionPane.ERROR_MESSAGE);
    }
    
    private boolean compruebaCampos(){
    	return chkCubierta.isSelected() || chkExterior.isSelected();
    }

    private javax.swing.JButton btGuardar;
    private javax.swing.JRadioButton chkCubierta;
    private javax.swing.JRadioButton chkExterior;
    private javax.swing.JLabel jDisponibilidad;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JComboBox jcDisponibilidad;
    private javax.swing.JComboBox jcbTipo;
    private javax.swing.JLabel jlbPista;
    private javax.swing.JLabel jlbTipo;
    // End of variables declaration//GEN-END:variables
}
