/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VentanaGrafica;

import java.util.ArrayList;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

import enums.BonoEnum;
import transfers.Socio;
import Control.ControladorAlquilerCompra;
import Control.ControladorUsuarios;

/**
 *
 * @author Cristina
 */
public class CompraBono extends javax.swing.JPanel {

	private ControladorAlquilerCompra controlAlquilerCompra;
	private ControladorUsuarios controlUsuarios;
	private ArrayList<Socio> listaSocios;
	
    /**
     * Creates new form CompraBono
     * @param muestraLista 
     * @param controlAlquilerCompra 
     */
    public CompraBono(ControladorUsuarios controlUsuarios, ControladorAlquilerCompra controlAlquilerCompra, boolean muestraLista) {
        this.controlUsuarios = controlUsuarios;
    	this.controlAlquilerCompra = controlAlquilerCompra;
    	initComponents();
        listaUsuarios.setVisible(muestraLista);
        etiquetaUsuarios.setVisible(muestraLista);
        jScrollPane1.setVisible(muestraLista);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        tituloCompraBono = new javax.swing.JLabel();
        etiquetaMeses = new javax.swing.JLabel();
        meses = new javax.swing.JComboBox();
        etiquetaPrecio = new javax.swing.JLabel();
        precio = new javax.swing.JLabel();
        etiquetaUsuarios = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaUsuarios = new javax.swing.JList();
        etiqeutaTipo = new javax.swing.JLabel();
        tipo = new javax.swing.JComboBox();
        botonComprar = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 204, 255));
        
        meses.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", 
        		"3", "6", "9", "12", "24"}));
        
        tituloCompraBono.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        tituloCompraBono.setText("COMPRA BONO");

        etiquetaMeses.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        etiquetaMeses.setText("Meses");

        etiquetaPrecio.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        etiquetaPrecio.setText("Precio");

        precio.setText("precio");

        etiquetaUsuarios.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        etiquetaUsuarios.setText("Usuarios");

        jScrollPane1.setViewportView(listaUsuarios);
        
        
        DefaultListModel<Socio> modeloLista = new DefaultListModel<Socio>();
    	listaSocios = controlUsuarios.listaSocios();
    	if(!listaSocios.isEmpty()){
    		for(int i = 0; i < listaSocios.size(); i++){
        		modeloLista.add(i, listaSocios.get(i));
        	}
    	}
       
    	listaUsuarios.removeAll();
        listaUsuarios.setModel(modeloLista);

        etiqeutaTipo.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        etiqeutaTipo.setText("Tipo");

        tipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PISCINA", "GIMNASIO" }));

        botonComprar.setText("Comprar Bono");
        botonComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonComprarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(tituloCompraBono))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(55, 55, 55)
                                        .addComponent(etiqeutaTipo)
                                        .addGap(32, 32, 32))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(etiquetaPrecio)
                                            .addComponent(etiquetaMeses))
                                        .addGap(18, 18, 18)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(meses, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(precio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tipo, 0, 99, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(67, 67, 67)
                                .addComponent(botonComprar)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(etiquetaUsuarios))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloCompraBono)
                .addGap(18, 18, 18)
                .addComponent(etiquetaUsuarios)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiqeutaTipo)
                    .addComponent(tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(meses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(etiquetaMeses))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(etiquetaPrecio)
                            .addComponent(precio))
                        .addGap(18, 18, 18)
                        .addComponent(botonComprar))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>                        

    private void botonComprarActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    	if(!listaUsuarios.isSelectionEmpty()){
	    	int a = Integer.parseInt((String) this.meses.getSelectedItem());
	    	Socio socio = listaSocios.get(this.listaUsuarios.getSelectedIndex());
	    	if(controlAlquilerCompra.compraBono(BonoEnum.valueOf(tipo.getSelectedItem().toString()), a, socio.getNick())){
	    		JOptionPane.showMessageDialog(null,  "Bono comprado","Exito", JOptionPane.INFORMATION_MESSAGE);
	    	}else{
	    		JOptionPane.showMessageDialog(null,  "Fallo","ERROR", JOptionPane.INFORMATION_MESSAGE);	    	
	    	}
    	}else
    		JOptionPane.showMessageDialog(null,  "Elige usuario","ERROR", JOptionPane.INFORMATION_MESSAGE);
    }                                            


    // Variables declaration - do not modify                     
    private javax.swing.JButton botonComprar;
    private javax.swing.JLabel etiqeutaTipo;
    private javax.swing.JLabel etiquetaMeses;
    private javax.swing.JLabel etiquetaPrecio;
    private javax.swing.JLabel etiquetaUsuarios;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList listaUsuarios;
    private javax.swing.JComboBox meses;
    private javax.swing.JLabel precio;
    private javax.swing.JComboBox tipo;
    private javax.swing.JLabel tituloCompraBono;
    // End of variables declaration                   
}
