/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VentanaGrafica;

import Control.ControladorAlquilerCompra;

/**
 *
 * @author Cristina
 */
public class CompraBono extends javax.swing.JPanel {

	ControladorAlquilerCompra control;
	
    /**
     * Creates new form CompraAbonoPiscina
     */
    public CompraBono(ControladorAlquilerCompra controlador) {
    	control = controlador;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        tituloCompraBono = new javax.swing.JLabel();
        etiquetaMeses = new javax.swing.JLabel();
        precio = new javax.swing.JTextField();
        etiquetaPrecio = new javax.swing.JLabel();
        compraBono = new javax.swing.JButton();
        meses = new javax.swing.JTextField();

        setBackground(new java.awt.Color(153, 204, 255));

        tituloCompraBono.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        tituloCompraBono.setText("Compra Bono");

        etiquetaMeses.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        etiquetaMeses.setForeground(new java.awt.Color(102, 102, 102));
        etiquetaMeses.setText("Meses");

        precio.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        precio.setForeground(new java.awt.Color(102, 102, 102));

        etiquetaPrecio.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        etiquetaPrecio.setForeground(new java.awt.Color(102, 102, 102));
        etiquetaPrecio.setText("Precio");

        compraBono.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        compraBono.setForeground(new java.awt.Color(102, 102, 102));
        compraBono.setText("Comprar Bono");
        compraBono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                compraBonoActionPerformed(evt);
            }
        });

        meses.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        meses.setForeground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(tituloCompraBono))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(etiquetaMeses, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                            .addComponent(etiquetaPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(precio, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                            .addComponent(meses)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(compraBono)))
                .addContainerGap(122, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloCompraBono)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etiquetaMeses, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(meses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(etiquetaPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addComponent(compraBono)
                .addContainerGap())
        );
    }// </editor-fold>                        

    private void compraBonoActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          


    // Variables declaration - do not modify                     
    private javax.swing.JButton compraBono;
    private javax.swing.JLabel etiquetaMeses;
    private javax.swing.JLabel etiquetaPrecio;
    private javax.swing.JTextField meses;
    private javax.swing.JTextField precio;
    private javax.swing.JLabel tituloCompraBono;
    // End of variables declaration                   
}
