/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package VentanaGrafica;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.sql.Connection;
import java.util.ArrayList;

import javax.swing.DefaultListModel;
import javax.swing.JFrame;

import transfers.Funcionario;
import transfers.Instalaciones;
import Control.ControladorAlquilerCompra;
import Control.ControladorClases;
import Control.ControladorInstalaciones;
import Control.ControladorMateriales;
import Control.ControladorUsuarios;

/**
 *
 * @author juanjose
 */
public class VentanaFuncionario extends javax.swing.JPanel {

	ControladorAlquilerCompra controlAlquilerCompra;
	ControladorMateriales controlMateriales;
	ControladorClases controlClases;
	ControladorInstalaciones controlInstalaciones;
	ControladorUsuarios controlUsuarios;
	private JFrame frame;
	private Connection con;
	private String nick;
	
    /**
     * Creates new form VentanaFuncionario
     * @param nick 
     */
    public VentanaFuncionario(Connection c, ControladorAlquilerCompra controlAlqComp, ControladorMateriales controlMat,
			ControladorClases controlCla, ControladorInstalaciones controlInst, ControladorUsuarios controlUsu, String nick) {
		this.nick = nick;
    	con = c;
    	controlUsuarios = controlUsu;
    	controlAlquilerCompra = controlAlqComp;
		controlMateriales = controlMat;
		controlClases = controlCla;
		controlInstalaciones = controlInst;
		panelCompraAbono = null;
		panelContratacionEntrenador = null;
		panelInstalacion = null;
		panelMaterial = null;
        initComponents();
        this.setVisible(true);
    }

	/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

    	bAlqInstalacion = new javax.swing.JButton();
        AlqMaterial = new javax.swing.JButton();
        ContEntrenador = new javax.swing.JButton();
        panelInterno = new javax.swing.JPanel();
        panelListas = new javax.swing.JPanel();
        scrListaDeportes = new javax.swing.JScrollPane();
        listaDeportes = new javax.swing.JList();
        scrListaHoras = new javax.swing.JScrollPane();
        listaHoras = new javax.swing.JList();
        HorasLibre = new javax.swing.JLabel();
        Deportes = new javax.swing.JLabel();
        btVerHoras = new javax.swing.JButton();
        CompraAbonoPisc = new javax.swing.JButton();
        Salir = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 204, 255));

        bAlqInstalacion.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        bAlqInstalacion.setForeground(new java.awt.Color(102, 102, 102));
        bAlqInstalacion.setText("Alquiler Instalacion");
        bAlqInstalacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	bAlqInstalacionActionPerformed(evt);
            }
        });

        AlqMaterial.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        AlqMaterial.setForeground(new java.awt.Color(102, 102, 102));
        AlqMaterial.setText("Alquiler Material");
        AlqMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlqMaterialActionPerformed(evt);
            }
        });

        ContEntrenador.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        ContEntrenador.setForeground(new java.awt.Color(102, 102, 102));
        ContEntrenador.setText("Contratacion Entrenador");
        ContEntrenador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContEntrenadorActionPerformed(evt);
            }
        });

        panelInterno.setBackground(new java.awt.Color(153, 204, 255));

        panelListas.setBackground(new java.awt.Color(153, 204, 255));

        listaDeportes.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Futbol7", "Futbol11", "Baloncesto", "Tenis", "Padel" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        scrListaDeportes.setViewportView(listaDeportes);

        listaHoras.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "11:00", "12:00", "13:00", "14:00", "21:00" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        scrListaHoras.setViewportView(listaHoras);

        HorasLibre.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        HorasLibre.setForeground(new java.awt.Color(102, 102, 102));
        HorasLibre.setText("Horas Libres");

        Deportes.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        Deportes.setForeground(new java.awt.Color(102, 102, 102));
        Deportes.setText("Deportes");

        btVerHoras.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        btVerHoras.setForeground(new java.awt.Color(102, 102, 102));
        btVerHoras.setText("Ver Horas");
        btVerHoras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVerHorasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelListasLayout = new javax.swing.GroupLayout(panelListas);
        panelListas.setLayout(panelListasLayout);
        panelListasLayout.setHorizontalGroup(
            panelListasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelListasLayout.createSequentialGroup()
                .addGroup(panelListasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelListasLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(Deportes)
                        .addGap(91, 91, 91)
                        .addComponent(HorasLibre))
                    .addGroup(panelListasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(scrListaDeportes, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(scrListaHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(btVerHoras)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        panelListasLayout.setVerticalGroup(
            panelListasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelListasLayout.createSequentialGroup()
                .addGroup(panelListasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelListasLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(btVerHoras))
                    .addGroup(panelListasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelListasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Deportes)
                            .addComponent(HorasLibre))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelListasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scrListaDeportes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(scrListaHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelInternoLayout = new javax.swing.GroupLayout(panelInterno);
        panelInterno.setLayout(panelInternoLayout);
        panelInternoLayout.setHorizontalGroup(
            panelInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInternoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelListas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelInternoLayout.setVerticalGroup(
            panelInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInternoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelListas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        CompraAbonoPisc.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        CompraAbonoPisc.setForeground(new java.awt.Color(102, 102, 102));
        CompraAbonoPisc.setText("CompraAbono");
        CompraAbonoPisc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CompraAbonoPiscActionPerformed(evt);
            }
        });

        Salir.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        Salir.setForeground(new java.awt.Color(102, 102, 102));
        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bAlqInstalacion, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AlqMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ContEntrenador))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(CompraAbonoPisc, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Salir))
                    .addComponent(panelInterno, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bAlqInstalacion)
                    .addComponent(AlqMaterial)
                    .addComponent(ContEntrenador))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelInterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Salir)
                    .addComponent(CompraAbonoPisc))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
    	System.exit(0);
    }//GEN-LAST:event_SalirActionPerformed

    private void bAlqInstalacionActionPerformed(java.awt.event.ActionEvent evt) {
    	panelInstalacion = new AlquilerInstalacion(controlAlquilerCompra);
    	panelListas.setVisible(false);
        quitaPaneles();
        panelInterno.setLayout(new BorderLayout());
        panelInterno.setSize(300, 300);
        panelInstalacion.setPreferredSize(new Dimension(400,300));
        this.setPreferredSize(new Dimension(500,400));
        panelInterno.add(panelInstalacion, BorderLayout.CENTER);
        panelInstalacion.setVisible(true);
    }

    private void AlqMaterialActionPerformed(java.awt.event.ActionEvent evt) {
    	panelMaterial = new AlquilerMaterial(controlAlquilerCompra);
    	panelListas.setVisible(false);
        quitaPaneles();
        panelInterno.setLayout(new BorderLayout());
        panelInterno.setSize(300, 300);
        panelMaterial.setPreferredSize(new Dimension(300,200));
        this.setPreferredSize(new Dimension(500,400));
        panelInterno.add(panelMaterial, BorderLayout.CENTER);
        panelMaterial.setVisible(true);
    }

    private void ContEntrenadorActionPerformed(java.awt.event.ActionEvent evt) {
    	panelContratacionEntrenador = new ContratacionEntrenador(controlAlquilerCompra, controlInstalaciones);
        panelListas.setVisible(false);
        quitaPaneles();
        panelInterno.setLayout(new BorderLayout());
        panelInterno.setSize(300, 300);
        panelContratacionEntrenador.setPreferredSize(new Dimension(300,200));
        panelInterno.add(panelContratacionEntrenador, BorderLayout.CENTER);
        panelContratacionEntrenador.setVisible(true);
    }

    private void btVerHorasActionPerformed(java.awt.event.ActionEvent evt) {
        ArrayList<Instalaciones> listaInstalaciones = controlInstalaciones.verHoras();
        if(listaInstalaciones != null){
        	DefaultListModel<String> modeloLista;
        	for(Instalaciones i: listaInstalaciones){
        		
        	}
        }
    }

    private void CompraAbonoPiscActionPerformed(java.awt.event.ActionEvent evt) {
    	panelCompraAbono = new CompraBono(controlAlquilerCompra);
        panelListas.setVisible(false);
        quitaPaneles();
        panelInterno.setLayout(new BorderLayout());
        panelInterno.setSize(300, 300);
        panelCompraAbono.setPreferredSize(new Dimension(400,300));
        panelInterno.add(panelCompraAbono, BorderLayout.CENTER);
        panelCompraAbono.setVisible(true);
    } 


	private void quitaPaneles() {
		if(panelCompraAbono != null)
			panelCompraAbono.setVisible(false);
		if(panelContratacionEntrenador != null)
			panelContratacionEntrenador.setVisible(false);
		if(panelInstalacion != null)
			panelInstalacion.setVisible(false);
		if(panelMaterial != null)
			panelMaterial.setVisible(false);
		
	}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AlqMaterial;
    private javax.swing.JButton bAlqInstalacion;
    private javax.swing.JButton CompraAbonoPisc;
    private javax.swing.JButton ContEntrenador;
    private javax.swing.JLabel Deportes;
    private javax.swing.JLabel HorasLibre;
    private javax.swing.JButton Salir;
    private javax.swing.JButton btVerHoras;
    private javax.swing.JList listaDeportes;
    private javax.swing.JList listaHoras;
    private javax.swing.JPanel panelInterno;
    private javax.swing.JPanel panelListas;
    private javax.swing.JScrollPane scrListaDeportes;
    private javax.swing.JScrollPane scrListaHoras;
    private CompraBono panelCompraAbono;
    private ContratacionEntrenador panelContratacionEntrenador;
    private AlquilerMaterial panelMaterial;
    private AlquilerInstalacion panelInstalacion;
    // End of variables declaration//GEN-END:variables
}
