/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VentanaGrafica;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.sql.Connection;

import javax.swing.JFrame;

import Control.ControladorAlquilerCompra;
import Control.ControladorClases;
import Control.ControladorInstalaciones;
import Control.ControladorMateriales;
import Control.ControladorUsuarios;


/**
 *
 * @author Cristina
 */
public class VentanaUsuario extends javax.swing.JPanel {

	private ControladorAlquilerCompra controlAlquilerCompra;
	private ControladorMateriales controlMateriales;
	private ControladorClases controlClases;
	private ControladorInstalaciones controlInstalaciones;
	private ControladorUsuarios controlUsuarios;
	private JFrame frame;
	private Connection con;
	private String nick;
	
    /**
     * Creates new form VentanaUsuario
     * @param c 
     * @param nick 
     */
	public VentanaUsuario(Connection c, ControladorAlquilerCompra controlAlqComp, ControladorMateriales controlMat,
			ControladorClases controlCla, ControladorInstalaciones controlInst, ControladorUsuarios controlUsu, String nick) {
		this.nick = nick;
    	con = c;
    	controlUsuarios = controlUsu;
    	controlAlquilerCompra = controlAlqComp;
		controlMateriales = controlMat;
		controlClases = controlCla;
		controlInstalaciones = controlInst;
        initComponents();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        tituloUsuario = new javax.swing.JLabel();
        botonAlquilerInst = new javax.swing.JButton();
        botonContrMonitor = new javax.swing.JButton();
        botonAlquMaterial = new javax.swing.JButton();
        botonBono = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        panelInterno = new javax.swing.JPanel();
        panelListas = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaDeportes = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaHoras = new javax.swing.JList();
        etiquetaDeportes = new javax.swing.JLabel();
        etiquetaHoras = new javax.swing.JLabel();
        botonClase = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 204, 255));

        tituloUsuario.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        tituloUsuario.setForeground(new java.awt.Color(102, 102, 102));
        tituloUsuario.setText("USUARIO");

        botonAlquilerInst.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        botonAlquilerInst.setForeground(new java.awt.Color(102, 102, 102));
        botonAlquilerInst.setText("Alquiler de instalacion");
        botonAlquilerInst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAlquilerInstActionPerformed(evt);
            }
        });

        botonContrMonitor.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        botonContrMonitor.setForeground(new java.awt.Color(102, 102, 102));
        botonContrMonitor.setText("Contratacion Monitor");
        botonContrMonitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonContrMonitorActionPerformed(evt);
            }
        });

        botonAlquMaterial.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        botonAlquMaterial.setForeground(new java.awt.Color(102, 102, 102));
        botonAlquMaterial.setText("Alquiler Material");
        botonAlquMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAlquMaterialActionPerformed(evt);
            }
        });

        botonBono.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        botonBono.setForeground(new java.awt.Color(102, 102, 102));
        botonBono.setText("Compra Bono");
        botonBono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBonoActionPerformed(evt);
            }
        });

        botonSalir.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        botonSalir.setForeground(new java.awt.Color(102, 102, 102));
        botonSalir.setText("Salir");
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });

        panelInterno.setBackground(new java.awt.Color(153, 204, 255));
        panelInterno.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        panelListas.setBackground(new java.awt.Color(153, 204, 255));

        listaDeportes.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Futbol7", "Futbol11", "Baloncesto", "Tenis", "Padel" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listaDeportes);

        listaHoras.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "11:00", "12:00", "13:00", "14:00", "21:00" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listaHoras.setToolTipText("");
        jScrollPane2.setViewportView(listaHoras);

        etiquetaDeportes.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        etiquetaDeportes.setForeground(new java.awt.Color(102, 102, 102));
        etiquetaDeportes.setText("Deportes");

        etiquetaHoras.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        etiquetaHoras.setForeground(new java.awt.Color(102, 102, 102));
        etiquetaHoras.setText("Horas Libres");

        javax.swing.GroupLayout panelListasLayout = new javax.swing.GroupLayout(panelListas);
        panelListas.setLayout(panelListasLayout);
        panelListasLayout.setHorizontalGroup(
            panelListasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelListasLayout.createSequentialGroup()
                .addGroup(panelListasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelListasLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelListasLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(etiquetaDeportes)
                        .addGap(36, 36, 36)
                        .addComponent(etiquetaHoras)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelListasLayout.setVerticalGroup(
            panelListasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelListasLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(panelListasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etiquetaDeportes, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(etiquetaHoras, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelListasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49))
        );

        javax.swing.GroupLayout panelInternoLayout = new javax.swing.GroupLayout(panelInterno);
        panelInterno.setLayout(panelInternoLayout);
        panelInternoLayout.setHorizontalGroup(
            panelInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInternoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelListas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );
        panelInternoLayout.setVerticalGroup(
            panelInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInternoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelListas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        botonClase.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        botonClase.setForeground(new java.awt.Color(102, 102, 102));
        botonClase.setText("Contratacion Clase");
        botonClase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonClaseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(54, 54, 54)
                            .addComponent(botonAlquilerInst))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(botonContrMonitor, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(botonSalir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonBono, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(botonClase, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonAlquMaterial, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tituloUsuario)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(panelInterno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tituloUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botonAlquilerInst)
                        .addGap(11, 11, 11)
                        .addComponent(botonContrMonitor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonClase)
                        .addGap(11, 11, 11)
                        .addComponent(botonAlquMaterial)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonBono)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonSalir))
                    .addComponent(panelInterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>                        

    private void botonAlquilerInstActionPerformed(java.awt.event.ActionEvent evt) {                                                  
    	panelInstalacion = new AlquilerInstalacion(controlUsuarios, controlClases, controlAlquilerCompra, controlInstalaciones, false);
    	panelListas.setVisible(false);
        quitaPaneles();
        panelInterno.setLayout(new BorderLayout());
        panelInterno.setSize(300, 100);
        panelInstalacion.setPreferredSize(new Dimension(100,300));
        this.setPreferredSize(new Dimension(50,100));
        panelInterno.add(panelInstalacion, BorderLayout.CENTER);
        panelInstalacion.setVisible(true);
    }                                                 

    private void botonContrMonitorActionPerformed(java.awt.event.ActionEvent evt) {                                                  
    	panelContratacionEntrenador = new ContratacionEntrenador(controlUsuarios, controlAlquilerCompra, controlInstalaciones, controlClases, false);
        panelListas.setVisible(false);
        quitaPaneles();
        panelInterno.setLayout(new BorderLayout());
        panelInterno.setSize(500, 500);
        panelContratacionEntrenador.setPreferredSize(new Dimension(500,500));
        this.setPreferredSize(new Dimension(500,500));
        panelInterno.add(panelContratacionEntrenador, BorderLayout.CENTER);
        panelContratacionEntrenador.setVisible(true);
    }                                                 

    private void botonAlquMaterialActionPerformed(java.awt.event.ActionEvent evt) {                                                  
    	panelMaterial = new AlquilerMaterial(controlMateriales, controlAlquilerCompra, controlUsuarios, false);
    	panelListas.setVisible(false);
        quitaPaneles();
        panelInterno.setLayout(new BorderLayout());
        panelInterno.setSize(500, 500);
        panelMaterial.setPreferredSize(new Dimension(500,300));
        this.setPreferredSize(new Dimension(50,100));
        panelInterno.add(panelMaterial, BorderLayout.CENTER);
        panelMaterial.setVisible(true);
    }                                                 

    private void botonBonoActionPerformed(java.awt.event.ActionEvent evt) {                                          
    	panelCompraAbono = new CompraBono(controlUsuarios, controlAlquilerCompra, false);
        panelListas.setVisible(false);
        quitaPaneles();
        panelInterno.setLayout(new BorderLayout());
        panelInterno.setSize(300, 300);
        panelCompraAbono.setPreferredSize(new Dimension(400,300));
        panelInterno.add(panelCompraAbono, BorderLayout.CENTER);
        panelCompraAbono.setVisible(true);
    }                                         

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {                                           
    	System.exit(0);
    }                                          

    private void botonClaseActionPerformed(java.awt.event.ActionEvent evt) {                                           
    	panelContratacionClases = new ContratacionClases(controlClases, controlUsuarios, controlAlquilerCompra, false);
    	panelListas.setVisible(false);
        quitaPaneles();
        panelInterno.setLayout(new BorderLayout());
        panelInterno.setSize(500, 500);
        panelContratacionClases.setPreferredSize(new Dimension(500,500));
        this.setPreferredSize(new Dimension(500,500));
        panelInterno.add(panelContratacionClases, BorderLayout.CENTER);
        panelContratacionClases.setVisible(true);
    }                                          

    private void quitaPaneles() {
		if(panelCompraAbono != null)
			panelCompraAbono.setVisible(false);
		if(panelContratacionEntrenador != null)
			panelContratacionEntrenador.setVisible(false);
		if(panelInstalacion != null)
			panelInstalacion.setVisible(false);
		if(panelMaterial != null)
			panelMaterial.setVisible(false);
		if(panelContratacionClases != null)
			panelContratacionClases.setVisible(false);
	}
    
    
    // Variables declaration - do not modify                     
    private javax.swing.JButton botonAlquMaterial;
    private javax.swing.JButton botonAlquilerInst;
    private javax.swing.JButton botonBono;
    private javax.swing.JButton botonClase;
    private javax.swing.JButton botonContrMonitor;
    private javax.swing.JButton botonSalir;
    private javax.swing.JLabel etiquetaDeportes;
    private javax.swing.JLabel etiquetaHoras;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList listaDeportes;
    private javax.swing.JList listaHoras;
    private javax.swing.JPanel panelInterno;
    private javax.swing.JPanel panelListas;
    private javax.swing.JLabel tituloUsuario;
    private CompraBono panelCompraAbono;
    private ContratacionEntrenador panelContratacionEntrenador;
    private AlquilerMaterial panelMaterial;
    private AlquilerInstalacion panelInstalacion;
    private ContratacionClases panelContratacionClases;
    // End of variables declaration                   
}
