/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package VentanaGrafica;

/**
 *
 * @author juanjose
 */
public class VentanaFuncionario extends javax.swing.JPanel {

    /**
     * Creates new form VentanaFuncionario
     */
    public VentanaFuncionario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AlqPista = new javax.swing.JButton();
        AlqMaterial = new javax.swing.JButton();
        CompraAbonoPisc = new javax.swing.JButton();
        CompraAbonoGym = new javax.swing.JButton();
        ContEntrenador = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        panelInterno = new javax.swing.JPanel();
        scrListaDeportes = new javax.swing.JScrollPane();
        listaDeportes = new javax.swing.JList();
        scrListaHoras = new javax.swing.JScrollPane();
        listaHoras = new javax.swing.JList();
        HorasLibre = new javax.swing.JLabel();
        Deportes = new javax.swing.JLabel();
        btVerHoras = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 204, 255));

        AlqPista.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        AlqPista.setForeground(new java.awt.Color(102, 102, 102));
        AlqPista.setText("Alquiler Pista");
        AlqPista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlqPistaActionPerformed(evt);
            }
        });

        AlqMaterial.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        AlqMaterial.setForeground(new java.awt.Color(102, 102, 102));
        AlqMaterial.setText("Alquiler Material");
        AlqMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlqMaterialActionPerformed(evt);
            }
        });

        CompraAbonoPisc.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        CompraAbonoPisc.setForeground(new java.awt.Color(102, 102, 102));
        CompraAbonoPisc.setText("Compra AbonoPiscina");
        CompraAbonoPisc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CompraAbonoPiscActionPerformed(evt);
            }
        });

        CompraAbonoGym.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        CompraAbonoGym.setForeground(new java.awt.Color(102, 102, 102));
        CompraAbonoGym.setText("Compra Abono Gimnasio");
        CompraAbonoGym.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CompraAbonoGymActionPerformed(evt);
            }
        });

        ContEntrenador.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        ContEntrenador.setForeground(new java.awt.Color(102, 102, 102));
        ContEntrenador.setText("Contratacion Entrenador");
        ContEntrenador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContEntrenadorActionPerformed(evt);
            }
        });

        Salir.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        Salir.setForeground(new java.awt.Color(102, 102, 102));
        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });

        panelInterno.setBackground(new java.awt.Color(153, 204, 255));

        listaDeportes.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Futbol7", "Futbol11", "Baloncesto", "Tenis", "Padel" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        scrListaDeportes.setViewportView(listaDeportes);

        listaHoras.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "11:00", "12:00", "13:00", "14:00", "21:00" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        scrListaHoras.setViewportView(listaHoras);

        HorasLibre.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        HorasLibre.setForeground(new java.awt.Color(102, 102, 102));
        HorasLibre.setText("Horas Libres");

        Deportes.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        Deportes.setForeground(new java.awt.Color(102, 102, 102));
        Deportes.setText("Deportes");

        btVerHoras.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        btVerHoras.setForeground(new java.awt.Color(102, 102, 102));
        btVerHoras.setText("Ver Horas");
        btVerHoras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVerHorasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelInternoLayout = new javax.swing.GroupLayout(panelInterno);
        panelInterno.setLayout(panelInternoLayout);
        panelInternoLayout.setHorizontalGroup(
            panelInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInternoLayout.createSequentialGroup()
                .addGroup(panelInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInternoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(scrListaDeportes, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(scrListaHoras, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(btVerHoras))
                    .addGroup(panelInternoLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(Deportes)
                        .addGap(91, 91, 91)
                        .addComponent(HorasLibre)))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        panelInternoLayout.setVerticalGroup(
            panelInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInternoLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(btVerHoras)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInternoLayout.createSequentialGroup()
                .addGap(0, 19, Short.MAX_VALUE)
                .addGroup(panelInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Deportes)
                    .addComponent(HorasLibre))
                .addGap(5, 5, 5)
                .addGroup(panelInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(scrListaHoras)
                    .addComponent(scrListaDeportes)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(CompraAbonoPisc, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(CompraAbonoGym, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Salir))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelInterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(AlqPista, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AlqMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ContEntrenador)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AlqPista)
                    .addComponent(AlqMaterial)
                    .addComponent(ContEntrenador))
                .addGap(18, 18, 18)
                .addComponent(panelInterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CompraAbonoPisc)
                    .addComponent(CompraAbonoGym)
                    .addComponent(Salir))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SalirActionPerformed

    private void AlqPistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlqPistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AlqPistaActionPerformed

    private void AlqMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlqMaterialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AlqMaterialActionPerformed

    private void ContEntrenadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContEntrenadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContEntrenadorActionPerformed

    private void btVerHorasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVerHorasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btVerHorasActionPerformed

    private void CompraAbonoPiscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CompraAbonoPiscActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CompraAbonoPiscActionPerformed

    private void CompraAbonoGymActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CompraAbonoGymActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CompraAbonoGymActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AlqMaterial;
    private javax.swing.JButton AlqPista;
    private javax.swing.JButton CompraAbonoGym;
    private javax.swing.JButton CompraAbonoPisc;
    private javax.swing.JButton ContEntrenador;
    private javax.swing.JLabel Deportes;
    private javax.swing.JLabel HorasLibre;
    private javax.swing.JButton Salir;
    private javax.swing.JButton btVerHoras;
    private javax.swing.JList listaDeportes;
    private javax.swing.JList listaHoras;
    private javax.swing.JPanel panelInterno;
    private javax.swing.JScrollPane scrListaDeportes;
    private javax.swing.JScrollPane scrListaHoras;
    // End of variables declaration//GEN-END:variables
}
